### ISSUE TITLE
AWS S3 Storage: Unable to generate ZafiraReport due to the out-of-dated email ftl template

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#409]
Setup zebrunner with AWS S3 storage with github and SMTP integration 

Steps:
1. Register organization qaprosoft 
2. Register repository
3. Run API or Web demo test
4. Verify that Zafira report is present for API, Web job
Actual result: Zafira report is not present

<img width="346" alt="Screen Shot 2021-02-11 at 7 01 29 PM" src="https://user-images.githubusercontent.com/32964663/107665393-721bf700-6c9e-11eb-9e90-1a3021f23c3c.png">

**Comment by vdelendik** [comment]
ZafiraReport can't be generated because export email ftl template was changed. For the setup with AWS S3 bucket as a storage we have to manually copy new template(s):
```
cd zebrunner
aws s3 cp reporting/minio-storage/configuration/minio/data/templates/test_run_results.ftl s3://your-bucket/templates/
```

related tickets are:
https://github.com/zebrunner/reporting/issues/2243
https://github.com/zebrunner/zebrunner/issues/405
https://github.com/zebrunner/zebrunner/issues/403

1. we already have step "6" in migration guide and also going to register current ticket as known issue for templates sync up

**Comment by vdelendik** [comment]
closing as appropriate workaround is declared in release notes
